### ISSUE TITLE
Can you write some example of Spark Streaming + Kafka Integration  (Kafka broker version 0.10.0 or higher)

### ISSUE THREAD

**Issue by Hungsiro506** [mkuthan/example-kafka#2]
Hi Marcin Kuthan, i have followed your examples guide but it has some changes in Spark Streaming and Kafka integration API. Can take time to write some examples for that new API. Thanks.

**Comment by mkuthan** [comment]
@Hungsiro506 - I would really like to update the example project to the latest Kafka and Spark but right now all my research time is invested in Kafka Streams. On the other side Structured Streaming provides Kafka sink out of the box, see: https://github.com/apache/spark/blob/master/external/kafka-0-10-sql/src/main/scala/org/apache/spark/sql/kafka010/KafkaWriteTask.scala

**Comment by LinMingQiang** [comment]
> Hi Marcin Kuthan, i have followed your examples guide but it has some changes in Spark Streaming and Kafka integration API. Can take time to write some examples for that new API. Thanks.
Can this help you?
https://github.com/LinMingQiang/spark-util

**Comment by Hungsiro506** [comment]
LinMingQuaing. Thanks, I have taken a look at it, very interesting project. Can you do more example with Flink intergrations ?

**Comment by LinMingQiang** [comment]
> LinMingQuaing. Thanks, I have taken a look at it, very interesting project. Can you do more example with Flink intergrations ?
Is this what you want?
https://github.com/LinMingQiang/flink-demo
